version: "2.1"

services:
  app:
    build: .
    container_name: example-app
    restart: always
    ports: 
      - 3000:3000
  db:
    image: mysql
    container_name: example-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
  mysql-data: