version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: example-app
    restart: always
    ports: 
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=example
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./:/app/
    command: 
      - npm run start:dev
  db:
    image: mysql
    container_name: example-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
  mysql-data: